// generated by "sampctl package init"
#include <open.mp>

enum EXTRA_ID_TYPE:MAX_EXTRA_ID_TYPES
{
	INVALID_EXTRA_ID_TYPE = -1,
	EXTRA_ID_TYPE_HOUSE,
	EXTRA_ID_TYPE_BUSINESS,
	EXTRA_ID_TYPE_MICROWAVE
};

#define STREAMER_ENABLE_TAGS

#include "streamer_item_extra_id.inc"

main() 
{
	// write code here and run "sampctl package build" to compile
	// then run "sampctl package run" to run it
	new STREAMER_TAG_AREA:areaId, EXTRA_ID_TYPE:type, value;
	areaId = CreateDynamicSphere(0.0, 0.0, 0.5, 10.0);
	SetItemExtraId(STREAMER_TYPE_AREA, areaId, EXTRA_ID_TYPE_HOUSE, 1337);
	GetItemExtraId(STREAMER_TYPE_AREA, areaId, type, value);
	GetPlayerExtraId(INVALID_PLAYER_ID, type, value);
}