// generated by "sampctl package init"
#include <open.mp>
#include <streamer>

// Definitions (Tags)
enum EXTRA_ID_TYPE
{
	EXTRA_ID_TYPE_ENTRANCE,
	EXTRA_ID_TYPE_HOUSE,
	EXTRA_ID_TYPE_BUSINESS
}

// Auto completion
#define EXTRA_ID_TYPE_ENTRANCE  (EXTRA_ID_TYPE:0)
#define EXTRA_ID_TYPE_HOUSE     (EXTRA_ID_TYPE:1)
#define EXTRA_ID_TYPE_BUSINESS  (EXTRA_ID_TYPE:2)

#include "item_extra_id.inc"

main() 
{
	// write code here and run "sampctl package build" to compile
	// then run "sampctl package run" to run it
	new STREAMER_TAG_AREA:areaId, EXTRA_ID_TYPE:type, value;
	SetStreamerItemExtraId(STREAMER_TYPE_AREA, areaId, EXTRA_ID_TYPE_ENTRANCE, 1337);
	GetStreamerItemExtraId(STREAMER_TYPE_AREA, areaId, type, value);
	GetPlayerStreamerItemExtraId(INVALID_PLAYER_ID, type, value);
}