// generated by "sampctl package init"
#include <open.mp>

#define STREAMER_ENABLE_TAGS
#include <streamer>

enum EXTRA_ID_TYPE:MAX_EXTRA_ID_TYPES
{
	INVALID_EXTRA_ID_TYPE = -1,
	EXTRA_ID_TYPE_ENTRANCE,
	EXTRA_ID_TYPE_HOUSE,
	EXTRA_ID_TYPE_BUSINESS,
};

#include "item_extra_id.inc"

main() 
{
	// write code here and run "sampctl package build" to compile
	// then run "sampctl package run" to run it
	new STREAMER_TAG_AREA:areaId, EXTRA_ID_TYPE:type, value;
	SetItemExtraId(STREAMER_TYPE_AREA, areaId, EXTRA_ID_TYPE_ENTRANCE, 1337);
	GetItemExtraId(STREAMER_TYPE_AREA, areaId, type, value);
	GetPlayerExtraId(INVALID_PLAYER_ID, type, value);
}